const listOfFeatures = [
    {
        name: "Attacks",
        list: [
            "Aqueous Blast",
            "Braggart Exemplary Finisher",
            "Briny Bolt",
            "Decrease Alchemical Crossbow Missed Attacks",
            "Glue Bomb",
            "Rooting Rune",
            "Shining Ammunition",
            "Wolf Jaws",
        ],
    },
    {
        name: "Damage",
        list: [
            "Bloodthirsty Rune",
            "Bottled Lightning",
            "Boulder Seed",
            "Crushing Rune",
            "Decrease Alchemical Crossbow",
            "Disrupting Rune",
            "Dread Ampoule Critical Hit",
            "Dread Ampoule Hit",
            "Exsanguinating Ammunition",
            "Fearsome Rune",
            "Frost Vial",
            "Ghost Charge",
            "Intimidating Strike",
            "Lay on Hands",
            "Necrotic Bomb",
            "Ooze Ammunition",
            "Remove Champion's Resistance",
            "Seedpod",
        ],
    },
    {
        name: "Skills",
        list: [

            "Bon Mot",
            "Catfolk Dance",
            "Dirty Trick",
            "Disarm",
            "Goblin Song",
            "Grapple",
            "Known Weaknesses",
            "Overdrive",
            "Panache",
            "Predictable",
            "Prone When Critical Fails Acrobatic Skill",
            "Subsist",
            "Tamper",
            "Terrified Retreat",
            "Treat Disease",
            "Trip",
            "Tumble Behind",
        ],
    },
    {
        name: "Spells",
        list: [


            "Aberrant Form",
            "Accelerating Touch",
            "Adapt Self",
            "Adaptive Ablation",
            "Aerial Form",
            "Agile Feet",
            "Albatross Curse",
            "Allegro",
            "Ancestral Form",
            "Ancestral Memories",
            "Angel Form",
            "Angelic Halo",
            "Angelic Wings",
            "Animal Feature",
            "Animal Form",
            "Ant Haul",
            "Anticipate Peril",
            "Apex Companion",
            "Arcane Countermeasure",
            "Armor of Bones",
            "Ash Form",
            "Athletic Rush",
            "Bane",
            "Battlefield Persistence",
            "Bind Undead",
            "Bless",
            "Blessing of Defiance",
            "Blood Ward",
            "Blur",
            "Boost Eidolon",
            "Bottle the Storm",
            "Bullhorn",
            "Canopy Crawler",
            "Celestial Brand",
            "Channeling Block",
            "Chromatic Armor",
            "Cinder Gaze",
            "Claws of the Otter",
            "Clawsong",
            "Cloak of Light",
            "Competitive Edge",
            "Conductive Weapon",
            "Cosmic Form",
            "Countless Eyes",
            "Courageous Anthem",
            "Daemon Form",
            "Dancing Shield",
            "Darkened Sight",
            "Darkvision",
            "Death Ward",
            "Deep Sight",
            "Demon Form",
            "Detect Magic",
            "Devil Form",
            "Devouring Dark Form",
            "Diabolic Edict",
            "Dinosaur Form",
            "Dirge of Doom",
            "Discern Secrets",
            "Divine Infusion From Spell",
            "Dragon Form",
            "Eat Fire",
            "Element Embodied",
            "Elemental Absorption",
            "Elemental Form",
            "Elemental Gift",
            "Elemental Motion",
            "Elephant Form",
            "Embrace the Pit",
            "Endure",
            "Enduring Might",
            "Energy Absorption",
            "Energy Aegis",
            "Enlarge",
            "Envenom Companion",
            "Euphoric Renewal",
            "Evolution Surge",
            "Extract Poison",
            "Face in the Crowd",
            "False Vitality",
            "Ferrous Form",
            "Fey Form",
            "Fiery Body",
            "Fire Shield",
            "Flame Barrier",
            "Flame Dancer",
            "Flame Wisp",
            "Flashy Disappearance",
            "Fleet Step",
            "Flicker",
            "Flurry of Claws",
            "Fly",
            "Forbidding Ward",
            "Foresight",
            "Fortify Summoning",
            "Gecko Grip",
            "Ghostly Shift",
            "Ghostly Weapon",
            "Glass Form",
            "Glass Shield",
            "Glimpse Weakness",
            "Glutton's Jaws",
            "Gravity Weapon",
            "Gray Shadow",
            "Guidance",
            "Guided Introspection",
            "Haste",
            "Healer's Blessing",
            "Heroism",
            "Hidden Mind",
            "Hidebound",
            "Hymn of Healing",
            "Illusory Disguise",
            "Illusory Shroud",
            "Infectious Enthusiasm",
            "Infuse Vitality",
            "Inner Upheaval",
            "Inscrutable Mask",
            "Insect Form",
            "Inside Ropes",
            "Instant Armor",
            "Iron Gut",
            "Juvenile Companion",
            "Lashunta's Life Bubble",
            "Levitate",
            "Life Boost",
            "Life Connection",
            "Life Link",
            "Life-Giving Form",
            "Lifelink Surge",
            "Light",
            "Lucky Number",
            "Magic Hide",
            "Magic Stone",
            "Magic's Vessel",
            "Malignant Sustenance",
            "Mimic Undead",
            "Mirror Image",
            "Monstrosity Form",
            "Moon Frenzy",
            "Mountain Resilience",
            "Musical Accompaniment",
            "Mystic Armor",
            "Nature Incarnate",
            "Necromancer's Generosity",
            "Nudge Fate",
            "Nudge the Odds",
            "Nymph's Token",
            "Oaken Resilience",
            "Object Memory",
            "One with the Land",
            "Ooze Form",
            "Organsight",
            "Penumbral Disguise",
            "Pest Form",
            "Phase Familiar",
            "Phoenix Ward",
            "Physical Boost",
            "Plant Form",
            "Pocket Library",
            "Practice Makes Perfect",
            "Primal Summons",
            "Prismatic Armor",
            "Prismatic Shield",
            "Protect Companion",
            "Protection",
            "Protective Ward",
            "Protector's Sphere",
            "Qi Form",
            "Qi Rush",
            "Rallying Anthem",
            "Rapid Adaptation",
            "Read the Air",
            "Regenerate",
            "Reinforce Eidolon",
            "Repel Metal",
            "Resist Energy",
            "Return the Favor",
            "Rousing Splash",
            "Runic Body",
            "Runic Weapon",
            "Sacred Form",
            "Safeguard Secret",
            "Sand Form",
            "See the Unseen",
            "Serrate",
            "Share Life",
            "Shield",
            "Shields of the Spirit",
            "Shifting Form",
            "Shillelagh",
            "Shrink",
            "Silence",
            "Song of Strength",
            "Soothe",
            "Soothing Words",
            "Speaking Sky",
            "Spiral of Horrors",
            "Spirit Sense",
            "Stabilize",
            "Stoke the Heart",
            "Stormwind Flight",
            "Summoner's Visage",
            "Sure Strike",
            "Swarm Form",
            "Sweet Dream",
            "Tailwind",
            "Tailwind 8 hours",
            "Take Root",
            "Tempest Cloak",
            "Tempest Form",
            "Tempt Fate",
            "Thermal Remedy",
            "Thermal Stasis",
            "Thicket of Knives",
            "Thundering Dominance",
            "Touch of the Moon",
            "Touch of the Void",
            "Translocate",
            "Traveler's Transit",
            "Tremorsense",
            "Triple Time",
            "Unblinking Flame Aura",
            "Unblinking Flame Ignition",
            "Unbreaking Wave Vapor",
            "Unfettered Movement",
            "Untamed Form",
            "Untamed Shift",
            "Untwisting Iron Augmentation",
            "Untwisting Iron Pillar",
            "Unusual Anatomy",
            "Vapor Form",
            "Vision of Weakness",
            "Vital Beacon",
            "Vital Luminance",
            "Warp Step",
            "Wash Your Luck",
            "Weapon Surge",
            "Wind Jump",
            "Wooden Fists",
            "Zealous Conviction",
        ],
    },
    {
        name: "Saving Throw",
        list: [

            "Aberrant Whispers",
            "Acknowledge Fan",
            "Agonizing Cries Aura Immunity",
            "Agonizing Despair",
            "Albatross Curse",
            "Alien Presence Aura Immunity",
            "Allergen Aura Immunity",
            "Alluring Scent Aura Immunity",
            "Ancestral Touch",
            "Animus Mine",
            "Appetizing Aroma Aura Immunity",
            "Aromatic Lure",
            "Ash Cloud",
            "Ashen Wind",
            "Aura of Angry Crystals Immunity",
            "Aura of Blinding Light Immunity",
            "Aura of Charm Immunity",
            "Aura of Doom Immunity",
            "Aura of Forgetfulness Immunity",
            "Aura of Peace Immunity",
            "Aura of Protection Immunity",
            "Aura of Sobs Immunity",
            "Aura of Whispers Immunity",
            "Baleful Glare Aura Immunity",
            "Befuddle",
            "Bestial Curse",
            "Blasting Stone",
            "Blight Aura Immunity",
            "Blinding Aura Immunity",
            "Blinding Halo Aura Immunity",
            "Blindness",
            "Blindpepper Bomb",
            "Blindpepper Bomb Blinded",
            "Blindpepper Bomb Dazzled",
            "Blood Vendetta",
            "Brawling Critical Specialization",
            "Breath of Silt Aura Immunity",
            "Breath of the Bog Aura Immunity",
            "Brilliant",
            "Bullying Bluster Aura Immunity",
            "Calm",
            "Calming Presence Aura Immunity",
            "Chattering Teeth Aura Immunity",
            "Commanding Presence Aura Immunity",
            "Critical Debilitation",
            "Curse of Boiling Blood",
            "Curtain of Calm Aura Immunity",
            "Cute But Deadly Aura Immunity",
            "Daze",
            "Daze Amped",
            "Deafness",
            "Death Stench Aura Immunity",
            "Deepest Fear Aura Immunity",
            "Dehydrate",
            "Desiccation Aura Immunity",
            "Despair Aura Immunity",
            "Destabilizing Field Aura Immunity",
            "Disorienting Faces Aura Immunity",
            "Divine Decree",
            "Divine Wrath",
            "Draining Presence Aura Immunity",
            "Dread Flickering Aura Immunity",
            "Ecstatic Hunger Aura Immunity",
            "Evil Eye",
            "False Authority Aura Immunity",
            "Fascination of Flame Aura Immunity",
            "Fear",
            "Fear Fleeing",
            "Fear the Sun",
            "Firearm Critical Specialization",
            "Flail Critical Specialization",
            "Frightful Presence",
            "Frightful Presence Aura Immunity",
            "Frost Rune",
            "Frostbite",
            "Game Hunter Dedication",
            "Gentle Facade Aura Immunity",
            "Gibbering Aura Immunity",
            "Gory Finish",
            "Great Despair Immunity",
            "Greater Thundering Rune",
            "Grieving Aura Immunity",
            "Hallucinatory Scale Dust Aura Immunity",
            "Hammer Critical Specialization",
            "Heavy Aura Immunity",
            "Ill Omen",
            "Ill Omen Immunity",
            "Jinx",
            "Laughing Fit",
            "Lay on Hands (Vs. Undead)",
            "Light Aura Immunity",
            "Loathsome Stench Aura Immunity",
            "Luminous Lure Aura Immunity",
            "Maddening Cacophony Aura Immunity",
            "Magic-Warping Aura Immunity",
            "Malevolent Mishaps Aura Immunity",
            "Malodorous Smoke Aura Immunity",
            "Masked Intentions Aura Immunity",
            "Menacing Guardian Aura Immunity",
            "Miasma Aura Immunity",
            "Miasma of Pollution Aura Immunity",
            "Mindfog Aura Immunity",
            "Mocking Laughter Aura Immunity",
            "Musk Aura Immunity",
            "Necrotic Runoff Aura Immunity",
            "Never Mind",
            "Noxious Scent Aura Immunity",
            "Odor of Rot Aura Immunity",
            "Ominous Footsteps Aura Immunity",
            "Pacifying Aura Immunity",
            "Pained Muttering Aura Immunity",
            "Painful Vibrations Deafened",
            "Painful Vibrations Sickened",
            "Paralyze",
            "Peaceful Aura Immunity",
            "Perfume Aura Immunity",
            "Petrify",
            "Phantom Pain",
            "Powerful Stench Aura Immunity",
            "Predatory Aura Immunity",
            "Psychogenic Secretions Aura Immunity",
            "Pungent Aura Immunity",
            "Putrid Stench Aura Immunity",
            "Ripping Gaze Aura Immunity",
            "Rotting Stench Aura Immunity",
            "Scarecrow's Leer Aura Immunity",
            "Scintillating Aura Immunity",
            "Scrutinizing Presence Aura Immunity",
            "Shatterstone",
            "Sibilant Whispers Aura Immunity",
            "Skunk Bomb",
            "Skunk Bomb Blinded",
            "Sling Critical Specialization",
            "Slow",
            "Smoke Aura Immunity",
            "Smoldering Haze Aura Immunity",
            "Smoldering Stench Aura Immunity",
            "Stench Immunity",
            "Stinky Sweat Aura Immunity",
            "Stunning Blows",
            "Stupefy",
            "Synesthesia",
            "Terrifying Gaze Aura Immunity",
            "Terrorspores Aura Immunity",
            "The Desert",
            "Thundering Rune",
            "Tremor",
            "Tympanic Heartbeat Aura Immunity",
            "Unfathomable Infinity Aura Immunity",
            "Unluck Aura Immunity",
            "Unnerving Presence Aura Immunity",
            "Unrest Aura Immunity",
            "Utter Despair Aura Immunity",
            "Water Pressure Aura Immunity",
            "Weeping Aura Immunity",
            "World-Shaking Throw",
        ],
    },
    {
        name: "Equipment",
        list: [

            "Aeon Stone (Black Pearl)",
            "Aeon Stone (Pink Rhomboid)",
            "Aeon Stone (Sprouting)",
            "Aeon Stone Resonance (Amplifying)",
            "Aeon Stone Resonance (Black Disc)",
            "Aeon Stone Resonance (Pearly White Spindle)",
            "Ancestral Geometry",
            "Animal Blind",
            "Anklets of Alacrity",
            "Arachnid Harness",
            "Architect's Pattern Book",
            "Barding of the Zephyr",
            "Batsbreath Cane",
            "Belt of the Five Kings",
            "Blast Suit",
            "Bloodhound Olfactory Stimulators",
            "Bloodseeker Beak",
            "Boots of Elvenkind",
            "Bracelet of Dashing",
            "Bracers of Missile Deflection",
            "Chatterer of Follies",
            "Clawed Bracers",
            "Cloak of Swiftness",
            "Codex of Unimpeded Sight",
            "Containment Contraption",
            "Crown of the Kobold King",
            "Deathdrinking",
            "Diplomat's Badge",
            "Dragonscale Amulet",
            "Dueling Cape",
            "Earplugs",
            "Emberheart",
            "Energizing",
            "Energizing Lattice",
            "Energy Adaptive",
            "Energy Robe of Electricity",
            "Energy Robe of Fire",
            "Enhanced Hearing Aids",
            "Fanged",
            "Flask of Fellowship",
            "Force Shield",
            "Ghost Lantern",
            "Ghost Scarf",
            "Hexing Jar",
            "Holy Chain",
            "Immortal Bastion",
            "Ivory Baton",
            "Leopard's Armor",
            "Morning Glow",
            "Obsidian Goggles",
            "Ochre Fulcrum Lens",
            "Portable Animal Blind",
            "Spellguard Blade",
            "Stubborn Skin",
            "Thurible of Revelation",
            "Tome of Restorative Cleansing",
            "Tremorsensors",
            "Triton's Conch",
            "Ugly Cute's Gift",
            "Vaultbreaker's Harness",
            "Viper Rapier",
            "Watery Form",
            "Winged Sandals",
            "Wyrm Claw - Armor",
        ],
    },
    {
        name: "Consumable",
        list: [

            "Ablative Armor Plating",
            "Alloy Orb",
            "Amphisbaena Spittle",
            "Antidote",
            "Antifungal Salve",
            "Antiplague",
            "Applereed Mutagen",
            "Apricot of Bestial Might",
            "Aromatic Ammunition",
            "Ascendant Dragon Spirit",
            "Assassin Vine Wine",
            "Auric Noodles",
            "Bestial Mutagen",
            "Blight Breath",
            "Blood Booster",
            "Bloodhound Mask",
            "Bomber's Eye",
            "Bottled Omen",
            "Boulderhead Bock",
            "Bravo's Brew",
            "Brewer's Regret",
            "Bronze Bull Pendant",
            "Cheetah's Elixir",
            "Choker Arm Mutagen",
            "Cinnamon Seers",
            "Clandestine Cloak",
            "Cloud Buns",
            "Cognitive Mutagen",
            "Cold Iron Blanch",
            "Covenant Tea",
            "Darkvision Elixir",
            "Deadweight Mutagen",
            "Delve Scale",
            "Demortification Oil",
            "Diplomat's Charcuterie",
            "Discord Fulu",
            "Dragon Pearl",
            "Dragon Throat Scale",
            "Dragon's Blood Pudding",
            "Dragonfly Fulu",
            "Dragonfly Potion",
            "Drakeheart Mutagen",
            "Drowsy Sun Eye Drops",
            "Eagle Eye Elixir",
            "Egg Cream Fizz",
            "Elixir of Life",
            "Elysian Dew",
            "Energized Cartridge",
            "Energizing Pill",
            "Energizing Tea",
            "Energy Mutagen",
            "Escape Fulu",
            "Eye of the Unseen",
            "Feyfoul",
            "Fire and Iceberg",
            "Frost Breath",
            "Fury Cocktail",
            "Galvanic Chew",
            "Gecko Potion",
            "Ghost Fowl Porridge",
            "Ghost Oil",
            "Ghostbane Fulu",
            "Ginger Chew",
            "Glow Rod",
            "Grindlegrub Steak",
            "Hydra Mutagen",
            "Ichthyosis Mutagen",
            "Impossible Cake",
            "Insight Coffee",
            "Iron Medallion",
            "Iron Wine",
            "Juggernaut Mutagen",
            "Lastwall Soup",
            "Life-Boosting Oil",
            "Malleable Mixture",
            "Mistform Elixir",
            "Mortalis Coin",
            "Necrotic Cap",
            "Numbing Tonic",
            "Ommatophoric Mutagen",
            "Pallesthetic Mutagen",
            "Phoenix Flask",
            "Potency Crystal",
            "Potion of Acid Resistance",
            "Potion of Cold Resistance",
            "Potion of Electricity Resistance",
            "Potion of Emergency Escape",
            "Potion of Fire Resistance",
            "Potion of Flying",
            "Potion of Minute Echoes",
            "Potion of Quickness",
            "Potion of Sonic Resistance",
            "Potion of Stable Form",
            "Potion of Swimming",
            "Prey Mutagen",
            "Quicksilver Mutagen",
            "Red-Rib Gill Mask",
            "Sanguine Mutagen",
            "Sea Touch Elixir",
            "Sense-Dulling Hood",
            "Serene Mutagen",
            "Shrinking Potion",
            "Silver Crescent",
            "Silver Salve",
            "Silvertongue Mutagen",
            "Sixfingers Elixir",
            "Skeptic's Elixir",
            "Soothing Toddy",
            "Soothing Tonic",
            "Sorcerous Sweets Candy",
            "Spiderfoot Brew",
            "Stalk Goggles",
            "Star of Cynosure",
            "Stone Body Mutagen",
            "Stone Fist Elixir",
            "Stormbreaker Fulu",
            "Taper of Sanctification",
            "Thawing Candle",
            "Theatrical Mutagen",
            "Thousand-Year Dragonroot",
            "Tiger Menuki",
            "Topology Protoplasm",
            "Tracker's Stew",
            "Tricky Liniment",
            "Tteokguk of Time Advancement",
            "Vapor Sphere",
            "Vengeful Demon's Tears",
            "Vermin Repellent Agent",
            "Viperous Elixir",
            "War Blood Mutagen",
            "Wemmuth Trinket",
            "Wine of the Blood",
            "Witch's Finger",
            "Wounding Oil",
        ],
    },
    {
        name: "Other",
        list: [

            "Absorb Memories",
            "Accept Echo",
            "Activate Defenses",
            "Adaptive Strike",
            "Aid",
            "Alchemical Crossbow",
            "Alchemical Strike",
            "Aldori Parry",
            "Anadi Venom",
            "Ancestral Journey",
            "Ancestral Response",
            "Anoint Ally",
            "Arcane Cascade",
            "Arcane Propulsion",
            "Armor in Earth",
            "Artificer's Command",
            "Assimilate Lava",
            "Aura of Command",
            "Avenge In Glory",
            "Avoid Notice",
            "Barbed Net",
            "Battle Cry",
            "Battlemage's Apotheosis",
            "Bend Time",
            "Blade Barrage",
            "Blessed Armament",
            "Blizzard Evasion",
            "Blood Frenzy",
            "Blood Fury",
            "Blood Magic",
            "Blood Soak",
            "Bloom Regeneration",
            "Bodyguard's Defense",
            "Bond In Light",
            "Bone Spikes",
            "Bone Swarm",
            "Bristle",
            "Brutal Rally",
            "Buckler Dance",
            "Bullet Dancer Stance",
            "Bully the Departed",
            "Bully's Rage",
            "Calculate Threats",
            "Call Upon the Brightness",
            "Cat Nap",
            "Catharsis",
            "Ceremony of Protection",
            "Channel Elements",
            "Channel The Godmind",
            "Chaotic Spell",
            "Clan's Edge",
            "Clue In",
            "Cobra Stance",
            "Cobra Stance (Cobra Envenom)",
            "Combat Grab",
            "Conduct Energy",
            "Consolidated Overlay Panopticon",
            "Consult The Stars",
            "Core Cannon",
            "Cover Tracks",
            "Crane Stance",
            "Crawl",
            "Crimson Shroud",
            "Cunning Fervor",
            "Cut from the Air",
            "Daily Obedience",
            "Daydream Trance",
            "Defend",
            "Defensive Advance",
            "Defensive Instincts",
            "Defensive Recovery",
            "Deific Conduit",
            "Deity's Protection",
            "Desert Wind",
            "Desperate Wrath",
            "Destined Kill",
            "Devise A Stratagem - Didactic Strike",
            "Devise a Stratagem",
            "Die Another Day",
            "Disarming Stance",
            "Disrupting Strikes",
            "Disruptive Stance",
            "Divine Aegis",
            "Divine Infusion",
            "Divine Strategy",
            "Divine Wings",
            "Dragon Stance",
            "Dragon's Rage Wings",
            "Drop Prone",
            "Dualborn",
            "Dueling Dance",
            "Dueling Parry",
            "Duelist's Challenge",
            "Earth Impulse Junction",
            "Elemental Assault",
            "Elemental Fervor",
            "Elementalist Dedication",
            "Emblazon Armament",
            "Energize Wings",
            "Energy Shot",
            "Entity's Resurgence",
            "Envenom Fangs",
            "Everstand Stance",
            "Excommunication",
            "Extravagant Parry",
            "Eye of the Arclords",
            "Fade Into Daydreams",
            "Fane's Fourberie",
            "Favorable Winds",
            "Fencer Exemplary Finisher",
            "Fervor of Force",
            "Follow the Expert",
            "Forever Furious",
            "Fortify Shield",
            "Fresh Produce",
            "Fulminating Shot",
            "Furnace Form",
            "Gathering Moss",
            "Geologic Attunement",
            "Ghost Strike",
            "Ghost Wrangler",
            "Ghosts in the Storm",
            "Giant's Lunge",
            "Giant's Stature",
            "Gorilla Stance",
            "Grab",
            "Graceful Poise",
            "Guardian's Deflection",
            "Guardian's Embrace",
            "Guided Skill",
            "Guided by the Stars",
            "Harden Flesh",
            "Hardwood Armor",
            "Harrow the Fiend",
            "Harrower Dedication",
            "Heaven's Thunder",
            "Heraldic Statue",
            "Heroic Recovery",
            "Hungry Goblin",
            "Hustle",
            "Hydraulic Deflection",
            "Impassable Wall Stance",
            "Impose Order (Psychic)",
            "Indomitable Spirit",
            "Intimidating Strike",
            "Investigate",
            "Ironblood Stance",
            "Jellyfish Stance",
            "Juvenile Flight",
            "Kip Up",
            "Liberating Step",
            "Lichen's Tenacity",
            "Life-Giving Magic",
            "Lingering Fury",
            "Lunging Stance",
            "Maiden's Mending",
            "Marshal Dedication",
            "Masquerade of Seasons Stance",
            "Masterful Hunter",
            "Metal Carapace",
            "Metallic Skin",
            "Mighty Rage",
            "Mobile Shot Stance",
            "Monastic Archer Stance",
            "Monster Warden",
            "Mountain Stance",
            "Mountain Stronghold",
            "Multishot Stance",
            "Mutate Weapon",
            "Nanite Surge",
            "Oracle curse",
            "Oracular Warning",
            "Orchard's Endurance",
            "Overpowering Fervor",
            "Paragon's Guard",
            "Peafowl Stance",
            "Pistol Twirl",
            "Point Blank Stance",
            "Poison Weapon",
            "Powder Punch Stance",
            "Prayer-Touched Weapon",
            "Precious Ammunition",
            "Predictable",
            "Prevailing Position",
            "Propulsive Leap",
            "Psi Strikes",
            "Psychic Rapport",
            "Radiant Circuitry",
            "Rage",
            "Rain of Embers Stance",
            "Raise a Tome",
            "Recall Under Pressure",
            "Reckless Abandon (Goblin)",
            "Reflective Ripple Stance",
            "Renewed Vigor",
            "Repair Module",
            "Repeat a Spell",
            "Replenishment of War",
            "Retributive Strike",
            "Ricochet Stance",
            "Root Magic",
            "Rose's Tranquility",
            "Rough Terrain Stance",
            "Saoc Astrology",
            "Scars of Steel",
            "Scout",
            "Scout - Exploration",
            "Screaming Skull",
            "Sea Glass Guardians",
            "Search",
            "Security",
            "Selfish Shield",
            "Shadow Sight",
            "Shattershields",
            "Sheathed in Light",
            "Shed Tail",
            "Shooting Stars Stance",
            "Six Pillars Stance",
            "Sky and Heaven Stance",
            "Smite",
            "Sniping Duo Dedication",
            "Soaring Flight",
            "Spark Fist",
            "Spike Skin",
            "Spin Tale",
            "Spiral Sworn",
            "Spirit Empathy",
            "Stand",
            "Starlight Armor",
            "Stoked Flame Stance",
            "Stone Body",
            "Stoney Deflection",
            "Striking Retribution",
            "Stumbling Stance",
            "Tail Toxin",
            "Tangled Forest Stance",
            "Tenacious Stance",
            "Thermal Nimbus",
            "Tidal Shield",
            "Tiger Stance",
            "Tiller's Drive",
            "Titanic Rage",
            "Towering Presence",
            "Track",
            "Tunnel Wall",
            "Twinned Defense",
            "Unleash Psyche",
            "Ursine Avenger Form",
            "Victorious Vigor",
            "Vitality-Manipulating Stance",
            "Vivacious Bravado",
            "Volatile Rage",
            "Walking the Cardinal Paths",
            "Watchful Gaze",
            "Weapon Infusion",
            "Whirling Blade Stance",
            "Whirlwind Stance",
            "Wings Of Air",
            "Wolf Stance",
        ],
    }
]

export const data = [
    {
        id: 1,
        title: 'PF2e Automations',
        img: '/pf2e-wiki/img/gear.svg',
        "description": "Module for automate action/feats/spells",
        "price": "free",
        html: "<strong>Module for automate action/feats/spells.</strong><hr/>" +
            "<i>Module has 250+ automated rules.</i><hr/>" +
            "<p>Apply effect/condition automatically, when fail saving throw/crit specialization/cast spell.</p>" +
            "<p>When module was installed, need to press Sync Rules button to apply new rules to system.</p>" +
            "<div class='flex'><img src='/pf2e-wiki/module/sync-message.png' alt='Sync Message' width='400'><img src='/pf2e-wiki/module/sync-btn.png' alt='Sync Btn' width='400'></div>" +
            "<p>By default, all rules and handlers are off</p>" +
            "<div class='flex'><img src='/pf2e-wiki/module/rules-empty.png' alt='rules empty' width='500'><img src='/pf2e-wiki/module/handlers.png' alt='rules empty' width='500'></div>" +
            "<p>To turn on rules, you could use Apply Suggestion/Activate All/Activate Filtered and after it press Save</p>" +
            "<p>Handlers could be activated only manually for now</p>" +
            "<p><pre><code>Hooks.on('ready', function () {\n" +
            "    if (game?.pf2eautomations?.registerMessageCreateHandler) {\n" +
            "        game.pf2eautomations.registerMessageCreateHandler('bane-test', async (message) => {\n" +
            "            console.log('handling banes spell');\n" +
            "        })\n" +
            "    }\n" +
            "})</code></pre></p>"
    },
    {
        id: 2,
        title: 'PF2e Hands Management (Reminder)',
        img: '/pf2e-wiki/img/hand.svg',
        "description": "Module to notify about hands management",
        "price": "free",
        html: "<p>Notify that player uses more than 2 hands</p>" +
            "<p>Notify that player can't cast spell because need free hand</p>" +
            "<p>Also notify when pc tries to use action when under specific conditions</p>"
    },
    {
        id: 3,
        title: 'PF2e Party Sheet Helper',
        img: '/pf2e-wiki/img/group.svg',
        "description": "Module for improving work with PF2e Party Sheet",
        "price": "free",
        html: "<p class='c'><strong>Module contains few feature to improve Party Sheet</strong></p>" +
            "<br/>" +
            "<p><strong>Roll template</strong></p>" +
            "<p>Create roll template when click on skill secret if Meta/Ctrl) (copy check if Shift)</p>" +
            "<video width='320' height='240' controls><source src='https://github.com/reyzor1991/pf2e-wiki/assets/6688366/58bc0bdc-a33a-4951-9e10-e79e0115b92f' type='video/mp4'></video>" +
            "<br/>" +
            "<p><strong>Button for create encounter for party</strong></p>" +
            "<br/>" +
            "<p><strong>Buttons to call Travel Duration Calculators</strong></p>" +
            "<br/>" +
            "<p><strong>Health Setting</strong></p>" +
            "<p>PCs see heath bar as status instead of numbers</p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/party/health-setting.png' alt=''><img class='scale-03' src='/pf2e-wiki/module/party/party-sheet-health.png' alt=''></div></p>" +
            "<br/>" +
            "<p><strong>Party Leader</strong></p>" +
            "<p>Show leader of party, leader of party is first in list</p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/party/leader-setting.png' alt=''><img class='scale-03' src='/pf2e-wiki/module/party/party-leader.png' alt=''></div></p>" +
            "<br/>" +
            "<p><strong>Hide Wealth from PCs</strong></p>" +
            "<br/>" +
            "<p><strong>Party Sharing</strong></p>" +
            "<video width='320' height='240' controls><source src='https://github.com/reyzor1991/pf2e-wiki/assets/6688366/c89e9243-b928-4a74-ac65-ac631174817d' type='video/mp4'></video>" +
            "<br/>" +
            "<p><strong>Subsytems</strong></p>" +
            "<p>Enable subsystem</p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/party/subsystem-setting.png' alt=''><img class='scale-03' src='/pf2e-wiki/module/party/sub1.png' alt=''><img class='scale-02' src='/pf2e-wiki/module/party/sub2.png' alt=''></div></p>" +
            "<video width='320' height='240' controls><source src='https://github.com/reyzor1991/pf2e-wiki/assets/6688366/45dc1fcc-3d75-4b54-be67-9bcf1ad1c038' type='video/mp4'></video>" +
            "<br/>" +
            "<p><strong>Inline Influence checks\n</strong></p>" +
            "<p><pre><code>@Check[type:diplomacy|dc:33|traits:action:influence,npc-name:NPC 1]{Make impression on an NPC 1}</code></pre></p>" +
            "<p><pre><code>@Check[type:diplomacy|dc:15|traits:action:chases,npc-name:Sajan]{Sajan scares crowd}</code></pre></p>" +
            "<p><i>action:influence</i> - necessary to trigger skill check</p>" +
            "<p><i>npc-name:NPC 1</i> - necessary to write to subsystem npc name</p>" +
            "<p><pre><code>Points of result\n" +
            "     criticalFailure: -1\n" +
            "     failure: 0\n" +
            "     success: 1\n" +
            "     criticalSuccess: 2" +
            "</code></pre></p>" +
            "<br/>" +
            "<p><strong>Achivments</strong></p>" +
            "<p>Create achivments for PCs</p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/party/ach-setting.png' alt=''><img class='scale-03' src='/pf2e-wiki/module/party/ach.png' alt=''></div></p>" +
            "<br/>" +
            "<p><strong>Show encounter</strong></p>" +
            "<p>Show base info about PCs in party</p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/party/enc-setting.png' alt=''><img class='scale-03' src='/pf2e-wiki/module/party/enc.png' alt=''></div></p>" +
            "<br/>" +
            "<p><strong>Afflictions</strong></p>" +
            "<p>Show afflictions(effects with affliction in name) applied to PCs</p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/party/aff-setting.png' alt=''><img class='scale-03' src='/pf2e-wiki/module/party/aff.png' alt=''></div></p>" +
            "<br/>" +
            "<p><strong>Show effects</strong></p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/party/eff-setting.png' alt=''><img class='scale-03' src='/pf2e-wiki/module/party/effects.png' alt=''></div></p>" +
            "<br/>" +
            "<p><strong>Show focus points</strong></p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/party/fp.png' alt=''></div></p>" +
            "<br/>" +
            "<p><strong>Show spell info</strong></p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/party/spellinfo.png' alt=''></div></p>" +
            "<br>" +
            "<p><strong>Print inventory</strong></p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/party/print-set.png' alt=''><img class='scale-03' src='/pf2e-wiki/module/party/print.png' alt=''><img class='scale-03' src='/pf2e-wiki/module/party/print-example.png' alt=''></div></p>" +
            "<br>" +
            "<p><strong>Hide general info</strong></p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/party/hide-set.png' alt=''></div></p>" +
            "<br>" +
            "<p><strong>Max Encumbrance</strong></p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/party/enc-setting.png' alt=''><img class='scale-03' src='/pf2e-wiki/module/party/encu.png' alt=''></div></p>" +
            "<br>" +
            "<p><strong>Store last skills</strong></p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/party/skills.png' alt=''></div></p>" +
            "<br>" +
            "<p><strong>Party points</strong></p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/party/points-set.png' alt=''><img class='scale-03' src='/pf2e-wiki/module/party/points.png' alt=''></div></p>" +
            "<br>" +
            "<p><strong>Damage All</strong></p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/party/damage.png' alt=''></div></p>" +
            "<br>" +
            "<br>"
    },
    {
        id: 4,
        title: 'Pf2e Kingmaker Helper',
        img: '/pf2e-wiki/img/crown.svg',
        "description": "Module for improving work Kingmaker module",
        "price": "free",
        html: "<p><strong>Colored Hexes</strong></p>" +
            "<p>Show colored hexes (toggled btn) :</p>" +
            "<p>- Reconnoitered as green (default setting)</p>" +
            "<p>- Mapped as blue (default setting)</p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/king/set.png' alt=''><img class='scale-03' src='/pf2e-wiki/module/king/def.png' alt=''></div></p>" +
            "<br>" +
            "<p><strong>Resources</strong></p>" +
            "<p>GM/PC views. PC see only resources with checkbox “Show Camps and Commodities to Players</p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/king/res.png' alt=''></div></p>" +
            "<br>" +
            "<p><strong>Features</strong></p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/king/fea.png' alt=''></div></p>" +
            "<br>" +
            "<p><strong>Prepare Campsite</strong></p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/king/camp.png' alt=''></div></p>" +
            "<br>"
    },
    {
        id: 5,
        title: 'PF2e Macros',
        img: '/pf2e-wiki/img/gear.svg',
        "description": "Module adds macros for improving action/feats",
        "price": "free",
        html: "<p><strong>Aid</strong></p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/macro/aid.png' alt=''></div></p>" +
            "<br>" +
            "<p><strong>Favorite weapon</strong></p>" +
            "<p>Set favorite weapons for macros - default weapon when run macros</p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/macro/fav.png' alt=''><img class='scale-03' src='/pf2e-wiki/module/macro/fav-set.png' alt=''></div></p>" +
            "<br>"
    },
    {
        id: 6,
        title: 'PF2e Troops Helper',
        img: '/pf2e-wiki/img/group.svg',
        "description": "Module for working with troops. Transformation/control",
        "price": "free",
        html: "<p class='c'><strong>Module handle logic about Create troop/Form up/and handle hp of troop</strong></p>" +
            "<br>" +
            "<p><strong>Create Troop</strong></p>" +
            "<p>Btn or macro</p>" +
            "<video width='320' height='240' controls><source src='https://github.com/reyzor1991/pf2e-wiki/assets/6688366/34de0215-c41d-40de-b77f-585266afd0a4' type='video/mp4'></video>" +
            "<br>" +
            "<p><strong>Form Up</strong></p>" +
            "<p>Macro</p>" +
            "<video width='320' height='240' controls><source src='https://github.com/user-attachments/assets/bc677993-a98e-4cb9-adff-a3aea563b0fe' type='video/mp4'></video>" +
            "<br>" +
            "<br>"
    },
    {
        id: 7,
        title: 'PF2e Summons Helper',
        img: '/pf2e-wiki/img/pentagram.svg',
        "description": "Module for Summon/Dismiss/Sustain minions",
        "price": "free",
        html: "<p class='c'><strong>Module notify about sustain summoned creature</strong></p>" +
            "<br/>" +
            "<p><strong>Settings</strong></p>" +
            "<p>Set available sources for summoning</p>" +
            "<p><div class='flex'><img class='scale-03' src='/pf2e-wiki/module/summon/sum.png' alt=''><img class='scale-03' src='/pf2e-wiki/module/summon/source.png' alt=''></div></p>" +
            "<br/>" +
            "<p><strong>Example of summoning</strong></p>" +
            "<video width='320' height='240' controls><source src='https://github.com/user-attachments/assets/1f2747c8-d32d-4b76-99f9-447951352e7d' type='video/mp4'></video>" +
            "<br/>" +
            "<p><strong>Mirror's Reflection</strong></p>" +
            "<video width='320' height='240' controls><source src='https://github.com/user-attachments/assets/829d1f11-aac0-4150-8d59-a5f0da910b30' type='video/mp4'></video>" +
            "<br/>" +
            "<p><strong>Sustain</strong></p>" +
            "<video width='320' height='240' controls><source src='https://github.com/reyzor1991/pf2e-wiki/assets/6688366/801ebb3f-418e-479b-9bfe-cb561d723f53' type='video/mp4'></video>" +
            "<br/>" +
            "<p><strong>Dismiss</strong></p>" +
            "<video width='320' height='240' controls><source src='https://github.com/reyzor1991/pf2e-wiki/assets/6688366/49a1a31e-44db-4c0b-857b-eab846cc10d1' type='video/mp4'></video>" +
            "<br/>" +
            "<br/>"
    },
    {
        id: 8,
        title: 'PF2e Reaction Checker',
        img: '/pf2e-wiki/img/gear.svg',
        "description": "Small module to notify that actor can use reaction",
        "price": "free",
        html: "<p></p>"
    },
    {
        id: 9,
        title: 'PF2e Dying',
        img: '/pf2e-wiki/img/skull.svg',
        "description": "Module for handling dying conditions",
        "price": "free",
        html: "<p></p>"
    },
    {
        id: 11,
        title: 'PF2e Weapon Trait Options',
        img: '/pf2e-wiki/img/trait.svg',
        "description": "Module add possibility to add missed modifications to attack/damage roll",
        "price": "free",
        html: "<p></p>"
    },
    {
        id: 12,
        title: 'PF2e Gatewalkers Helper',
        img: '/pf2e-wiki/img/group.svg',
        "description": "Module provide feature for handling Devian Feats",
        "price": "free",
        html: "<p></p>"
    },
    {
        id: 13,
        title: 'PF2e Message Editor',
        img: '/pf2e-wiki/img/message.svg',
        "description": "Module for editing messages in chat",
        "price": "free",
        html: "<p></p>"
    },
    {
        id: 14,
        title: 'PF2e Initiative Effect',
        img: '/pf2e-wiki/img/2d6.svg',
        "description": "Module for homebrew rule, apply effect when roll 1/20 on initiative",
        "price": "free",
        html: "<p></p>"
    },
    {
        id: 15,
        title: 'PF2e Eidolon Helper',
        img: '/pf2e-wiki/img/pentagram.svg',
        "description": "Module for improving work with Eidolons",
        "price": "free",
        html: "<p></p>"
    },
    {
        id: 16,
        title: 'PF2e Flip Token',
        img: '/pf2e-wiki/img/flip.svg',
        "description": "Module to flip token image",
        "price": "free",
        html: "<p></p>"
    },
    {
        id: 17,
        title: 'PF2e Automations (Patreon)',
        img: '/pf2e-wiki/img/gear.svg',
        "description": "Module for automate action/feats/spells",
        "price": "patreon",
        html: "<strong>Module for automate action/feats/spells.</strong><hr/>" +
            "<i>Module has 900+ automated rules.</i><hr/>" +
            "<p>Apply effect/condition automatically, when fail saving throw/crit specialization/cast spell.</p>" +
            "<p>When module was installed, need to press Sync Rules button to apply new rules to system.</p>" +
            "<div class='flex'><img src='/pf2e-wiki/module/sync-message.png' alt='Sync Message' width='400'><img src='/pf2e-wiki/module/sync-btn.png' alt='Sync Btn' width='400'></div>" +
            "<p>By default, all rules and handlers are off</p>" +
            "<div class='flex'><img src='/pf2e-wiki/module/rules-empty.png' alt='rules empty' width='500'><img src='/pf2e-wiki/module/handlers.png' alt='rules empty' width='500'></div>" +
            "<p>To turn on rules, you could use Apply Suggestion/Activate All/Activate Filtered and after it press Save</p>" +
            "<p><strong>Recomendation</strong> Click Activate All Rules after it click Apply Suggestions (Deactivate only) and save rules</p>" +
            "<p>Handlers could be activated only manually for now</p>" +
            "<p><pre><code>Hooks.on('ready', function () {\n" +
            "    if (game?.pf2eautomations?.registerMessageCreateHandler) {\n" +
            "        game.pf2eautomations.registerMessageCreateHandler('bane-test', async (message) => {\n" +
            "            console.log('handling banes spell');\n" +
            "        })\n" +
            "    }\n" +
            "})</code></pre></p>"+
            "<h3>List of features</h3>"+
            "<br/>"+
            listOfFeatures.map(e=>{
                return `<details><summary>${e.name}</summary>${e.list.map(ee=>`<p>* ${ee}</p>`).join("")}</details>`
            }).join("")
    },
    {
        id: 18,
        title: 'PF2e Recall Knowledge',
        img: '/pf2e-wiki/img/scroll.svg',
        "description": "Module for handling Recall Knowledge logic",
        "price": "patreon",
        html: "<p></p>"
    },
    {
        id: 19,
        title: 'Pf2e Terrains',
        img: '/pf2e-wiki/img/mountain.svg',
        "description": "Module adds new type of regions",
        "price": "patreon",
        html: "<p></p>"
    },
    {
        id: 20,
        title: 'Pf2e Target Helper',
        img: '/pf2e-wiki/img/target.svg',
        "description": "Module for improving work saving throws/applying damage",
        "price": "patreon",
        html: "<p></p>"
    },
    {
        id: 21,
        title: 'PF2e Special',
        img: '/pf2e-wiki/img/gear.svg',
        "description": "",
        "price": "patreon",
        html: "<p></p>"
    },
    {
        id: 22,
        title: 'PF2e NPC Improvements',
        img: '/pf2e-wiki/img/group.svg',
        "description": "Module add NPC Sheet improvement",
        "price": "patreon",
        html: "<p></p>"
    },
    {
        id: 23,
        title: 'PF2e Monster Designer',
        img: '/pf2e-wiki/img/monster.svg',
        "description": "Module improves creating of new monsters and transforming exists",
        "price": "patreon",
        html: "<p></p>"
    },
    {
        id: 24,
        title: 'PF2e Measure Helper',
        img: '/pf2e-wiki/img/mountain.svg',
        "description": "Module for working with templates",
        "price": "patreon",
        html: "<p></p>"
    },
    {
        id: 25,
        title: 'PF2e Item Processor',
        img: '/pf2e-wiki/img/gear.svg',
        "description": "Module handles work with armors/runes/materials",
        "price": "patreon",
        html: "<p></p>"
    },
    {
        id: 26,
        title: 'PF2e Item Processor',
        img: '/pf2e-wiki/img/armor.svg',
        "description": "Module handles work with armors/runes/materials",
        "price": "patreon",
        html: "<p></p>"
    },
    {
        id: 27,
        title: 'PF2e Condition Converter',
        img: '/pf2e-wiki/img/gear.svg',
        "description": "Module for converting condition to effects",
        "price": "patreon",
        html: "<p></p>"
    },
    {
        id: 28,
        title: 'PF2e Campaign Statistics',
        img: '/pf2e-wiki/img/scroll.svg',
        "description": "Module for saving encounter/base statistics",
        "price": "patreon",
        html: "<p></p>"
    },
    {
        id: 29,
        title: 'PF2e Additional automations',
        img: '/pf2e-wiki/img/gear.svg',
        "description": "Module adds specific automations like blind roll/flat checks",
        "price": "patreon",
        html: "<p></p>"
    },
    {
        id: 30,
        title: 'PF2e Charactermancer',
        img: '/pf2e-wiki/img/group.svg',
        "description": "Module for comfortable level up of character",
        "price": "patreon",
        html: "<p></p>"
    },
    {
        id: 31,
        title: 'Novel messages',
        img: '/pf2e-wiki/img/scroll.svg',
        "description": "Show messages as popups",
        "price": "patreon",
        html: "<p></p>"
    },
    {
        id: 32,
        title: 'PF2e Animist',
        img: '/pf2e-wiki/img/group.svg',
        "description": "Handling Animist class",
        "price": "free",
        html: "<p></p>"
    },
    {
        id: 99,
        title: 'Pseudo Afflictions',
        img: '/pf2e-wiki/img/skull.svg',
        "description": "Module for improving work with afflictions.",
        "price": "patreon",
        html: "<p></p>"
    }
]